#!/bin/sh

# Put this file in /var/root/bin on your tester drive.  Make sure this is in root's path.

# Test to see if we can write to /
touch /var/netboot/tmp_write_test

if [ -e /var/netboot/tmp_write_test ]
then
	# If that succeeded, remove our test file
	rm /var/netboot/tmp_write_test
else
	MOUNT_FROM="$(ipconfig netbootoption shadow_mount_path 2>&1)"
	if [ -n $MOUNT_FROM ]
	then
		# Booted from a drive
		echo "Booted from a tester drive.  Mounting rw..."
		mount -uw /
	else
		# Netbooted
		echo "Netbooted.  Connecting to network share..."
		mount_network_share
		mount -uw /
		
		while [ "`df -l | awk '/\/private\/var\/netboot$/ { if ( $1 ~ /^afp/ ) print \"yes\"; else print \"no\"; }'`" = "yes" ]
		do
			if [ "`df -l | awk '/\/private\/var\/netboot$/ { if ( $1 ~ /\/dev\/disk/ ) print \"yes\"; else print \"no\"; }'`" = "yes" ]
			then
				echo "Failed to mount netboot volume.  Script can't run properly."
			else
				echo "Waiting for netboot volume to finish mounting..."
				sleep 1
			fi
		done
	fi
fi

# Run the script that is most likely located on the server.  Functioning this way allows
# scripts to be updated without requiring a rebuild of the netboot image.
/var/netboot/bin/test_ram_hd
