#!/bin/sh

# Put this file in /var/root/bin on your tester drive.  Make sure this is in root's path.

# Test to see if we can write to /
touch /var/netboot/tmp_write_test

if [ -e /var/netboot/tmp_write_test ]
then
	# If that succeeded, remove our test file
	rm /var/netboot/tmp_write_test
else
	# If that didn't succeed, try to mount root as writeable.  This will spew out a ton of
	# errors if netbooted.  Therefore, if this script is going on a netboot image, remove
	# the following one line to reduce errors.  Note that everything will still work fine,
	# even with the error messages, so it's not a big deal either way; it just freaks
	# people out.
	mount -uw /
	
	# This won't do much of anything if not netbooted
	mount_network_share
fi

# Run the script that is most likely located on the server.  Functioning this way allows
# scripts to be updated without requiring a rebuild of the netboot image.
/var/netboot/bin/test_ram_hd
